name: Claude Code Orchestrator

on:
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history needed
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure git for GitHub Actions
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure branch exists
        run: |
          BRANCH="claude/issue-${{ github.event.issue.number }}"
          git fetch origin main
          if ! git ls-remote --exit-code origin "$BRANCH"; then
            echo "Creating new branch $BRANCH"
            git checkout -b "$BRANCH" origin/main
            git push origin "$BRANCH"
          else
            echo "Branch $BRANCH already exists, skipping creation"
          fi

      - name: Run Claude Overseer
        id: claude
        uses: anthropics/claude-code-action@beta
        continue-on-error: true
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          additional_permissions: |
            actions: read
          model: "claude-sonnet-4"
          custom_instructions: |
            You are the overseer.
            - When an issue is opened, read its title and body.
            - Immediately call the task-orchestrator agent to handle the issue.
            - Create or update branches or PRs as needed.
            - Summarize results in a GitHub comment.
            Available agents:
            - /agents/frontend-builder.yaml
            - /agents/project-reality-manager.yaml
            - /agents/task-orchestrator.yaml
            - /agents/fastapi-langgraph-builder.yaml
            - /agents/fullstack-validator.yaml
            - /agents/task-completion-validator.yaml
            - /agents/test-generator-agent.yaml
