name: Claude Code Orchestrator

on:
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude:
    if: |
      (github.event_name == 'issues' && github.event.action == 'opened') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history so branch creation and comparison work

      - name: Run Claude Orchestrator
        id: claude
        uses: anthropics/claude-code-action@beta
        continue-on-error: true  # Prevent workflow from failing if branch is missing
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          additional_permissions: |
            actions: read
          model: "claude-sonnet-4"
          custom_instructions: |
            You are the OrchestratorAgent.
            - When an issue is opened, read its title and body.
            - Match the request to one or more worker agents in /agents.
            - Call their logic to implement code changes, tests, or validation.
            - Create or update branches or PRs as needed.
            - Summarize results in a GitHub comment.
            Available agents:
            - /agents/backend_agent.yaml       # Ensure branch creation logic exists in agents
            - /agents/frontend_agent.yaml
            - /agents/validator_agent.yaml
            - /agents/reality_manager.yaml
            - /agents/test_creator.yaml
            - /agents/webscraping_validator.yaml
